### ACCOUNT

### Public List
POST /api/category/list HTTP/1.1
Host: localhost:3000 

### Add
POST /api/admin/category/add HTTP/1.1
Host: localhost:3000
Authorization: Bearer 
Content-Type: application/json

{
    "title": "channel 1"
}

### Find
POST /api/admin/category/get/1 HTTP/1.1
Host: localhost:3000
Authorization: Bearer 

### Update
POST /api/admin/category/update HTTP/1.1
Host: localhost:3000
Authorization: Bearer 
Content-Type: application/json

{
    "id": 1,
    "title": "category 1"
}

### Remove
POST /api/admin/category/remove/1 HTTP/1.1
Host: localhost:3000
Authorization: Bearer 

### Permanently Delete
POST /api/admin/category/delete/1 HTTP/1.1
Host: localhost:3000
Authorization: Bearer 


### Get Thumbnail
POST /api/category/thumbnail/test-1600177653355.png HTTP/1.1
Host: localhost:3000


### Upload Thumbnail
POST /api/admin/category/upload-thumbnail/1 HTTP/1.1
Host: localhost:3000
Authorization: Bearer 
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png

< ./files/test.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--